import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '📖 Overview',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'overview/intro',
          label: 'Introduction',
        },
        {
          type: 'doc',
          id: 'overview/business-domain',
          label: 'Business Domain',
        },
        {
          type: 'doc',
          id: 'overview/technology-stack',
          label: 'Technology Stack',
        },
      ],
    },
    {
      type: 'category',
      label: '🏗️ Architecture',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'architecture/clean-architecture',
          label: 'Clean Architecture',
        },
      ],
    },
    {
      type: 'category',
      label: '🔐 Security',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'security/authentication-flow',
          label: 'Authentication Flow',
        },
      ],
    },
    {
      type: 'category',
      label: '💻 Development',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'development/getting-started',
          label: 'Getting Started',
        },
      ],
    },
    {
      type: 'category',
      label: '📑 API Reference',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api-reference',
        },
      ],
    },
  ],
};

export default sidebars;
